# TensorFlow Fundamentals
In this notebook, we're going to cover some of the most fundamenta concepts of tensors using TensorFlow
More specifically, we're going to cover;
- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors & Numpy
- Using @tf.functions (a way to speed up your regular Python Functions)
- Using GPUs with TensorFlow (or TPUs)
- Exercises to try for yourself

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

ModuleNotFoundError: No module named 'tensorflow'

In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the nu ber of dimentions of a tensor (ndims stands for number of dimensions)
scalar.ndim

0

In [7]:
# Create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [12]:
# Create a matrix, it has more than one dimension
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>